services:
    app:
        image: alexiscreoulo/clipcloud:latest
        ports:
            - "4500:4500"
        volumes:
            - sqlite-data:/app/DB
        env_file:
            - .env
        depends_on:
            - redis

redis:
    image: redis:7
    ports:
        - "6739:6739"
    volumes:
        - redis-data:/data

volumes:
    sqlite-data:
    redis-data:
