services:
  app:
    image: alexiscreoulo/clipcloud:latest
    ports:
      - "4500:4500"
    volumes:
      - db-data:/app/DB
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:  